# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # specify your project's Java version

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: TMDBExercise

      - name: Install dependencies
        run: ./gradlew dependencies
        working-directory: TMDBExercise

      - name: Run ktlint
        run: ./gradlew ktlintCheck
        working-directory: TMDBExercise

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: Testable APK
          path: /home/runner/work/2coders-ecercise/2coders-ecercise/TMDBExercise/app/build/reports/ktlint/ktlintAndroidTestSourceSetCheck/ktlintAndroidTestSourceSetCheck.txt
